translating workshops into pt-br
NuevoFoundation/workshops pull request #392
Opened 2023-07-17 18:54 UTC by caioortiz27

2023-09-12 18:13 UTC, ozhang22 reviewed
Left a few comments on files which are not yet translated.

I highly suggest getting Paulo and Joao to split reviewing the text for grammar and spelling.

2023-09-13 11:18 UTC, aminueza commented
@caioortiz27 do you plan to continue translating to pt-br?

2023-09-13 17:28 UTC, Renato3005 requested changes
Appendix and Index reviewd

2023-09-13 17:28 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/Appendix.md
> +Imagine que o nosso circuito é uma peça de teatro. Antes da apresentação final diante de uma plateia, precisamos de um lugar para praticar. É aqui que entra a tábua de pão.
Fix "tábua de pão". Suggestion: "placa de ensaio"

2023-09-13 17:28 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/Appendix.md
> ++ Breadboards são plataformas simples que podemos usar para construir circuitos temporários para teste e depuração antes de finalizar nosso projeto e soldá-lo permanentemente (soldar) juntos.
"soldá-lo", and then "(soldar)" is redundant

2023-09-13 17:28 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/Appendix.md
> ++ Cada uma das linhas numeradas na tábua de pão, mostrada a amarelo, contém 5 orifícios de alfinetes. Cada orifício de pino em uma linha (linha amarela) é conectado aos outros orifícios de pino nessa
Fix "alfinetes". Suggestion: "pinos".

2023-09-13 17:28 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/Appendix.md
> +![Alt Text: Imagem de uma tábua de pão sem linhas](../img/img16.png)
Fix "tábua de pão"

2023-09-13 17:28 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/Appendix.md
> +![Alt Text: Imagem de um breadboad](../img/breadboard.png)
Translate "breadboard"

2023-09-13 17:28 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/Appendix.md
> ++ O LED tem 2 derivações: o Ânodo e o cátodo.
The LED has 2 leads, which in this case, means "terminais", not "derivações"

2023-09-13 17:28 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/Appendix.md
> ++ Um resistor tem 2 derivações, mas é omnidirecional. Em outras palavras, não importa qual chumbo você anexa à tensão mais alta.
Resistor has 2 leads, "terminais"

2023-09-13 17:28 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/_index.md
> +Hoje trabalharemos em algumas atividades para mostrar algumas das capacidades desta plataforma. Começaremos pequenos e simples e construiremos para maiores e mais complexos. Você aprenderá todas as i
"mudar algumas coisas para ver o que é diferente" doesn't fit it well. Suggestion: "mudar alguns parâmetros para ver o que muda"

2023-09-13 17:28 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/_index.md
> +`Elegoo` O Kit Super Iniciante de Projeto UNO com Tutorial para Arduino inclui todo o hardware (com exceção do computador)
"`Elegoo` O Kit Super Iniciante de Projeto UNO" is a product, I suggest to not translate it. Suggestion: "`Elegoo` UNO Project Super Starter Kit"

2023-09-14 18:42 UTC, Renato3005 requested changes
All activities reviewd

2023-09-14 18:42 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/activity-4.md
> + * LCD Ativar pino para pino digital 8
Fix "Ativar". Suggestion: "pino de ativação".

2023-09-14 18:42 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/activity-4.md
> + * LCD D4 pino para pino digital 9
Reorder the words. Suggestion: "Pino D4 do LCD para pino digital 9". Do the same in lines 33, to 38.

2023-09-14 18:42 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/activity-4.md
> + * LCD VSS pino à terra
"à terra" isn't the correct meaning. Suggestion: "ao terra".

2023-09-14 18:42 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/activity-4.md
> + * LCD R / W pino ao solo
Fix "ao solo". Suggestion: "ao terra"

2023-09-14 18:42 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/activity-4.md
> + * termina a +5V e terra
Fix "e terra"

2023-09-14 18:42 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/activity-4.md
> + * limpador para pino VO LCD (pino 3)
add "VO **do** LCD". Confirm that steps on line 40 and 41 are understandable

2023-09-14 18:42 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/activity-4.md
> +Biblioteca adicionada originalmente 18 abr 2008
add "originalmente **em** 18 abr 2008"

2023-09-14 18:42 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/activity-4.md
> + biblioteca modificada 5 jul 2009
add "modificada **em** 5 jul"

2023-09-14 18:42 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/activity-4.md
> + exemplo adicionado 9 jul 2009
add "adicionado **em** 9 jul"

2023-09-14 18:42 UTC, Renato3005 commented on content/brazilian-portuguese/arduino/activity-4.md
> + modificado 22 nov 2010
add "modificado **em** 22 nov"

2023-09-20 23:25 UTC, caioortiz27 commented
> @caioortiz27 do you plan to continue translating to pt-br?

@aminueza hello Amanda, yes - I would like to sync with you and Paulo on the next steps

2023-09-22 16:07 UTC, closed without merging