Ale translation spanish
NuevoFoundation/workshops pull request #404
Opened 2023-09-14 02:30 UTC by alemcuevas

This is the completed workshop of android tic tac toe translated to Spanish.

2023-09-14 16:45 UTC, ozhang22 reviewed
Initial review - mostly pointing out missing translations and formatting quirks.

2023-09-14 16:45 UTC, ozhang22 commented on content/espanol/android-tictactoe/android-setup.md
> +## Open Project Files
To translate

2023-09-14 16:45 UTC, ozhang22 commented on content/espanol/android-tictactoe/android-setup.md
> +<img src="../resources/_gen/images/edit_env_variable.png" height="30%" width="30%" title="Edit system environment variables" alt="Edit system environment variables"/>
Please translate all alt and title text as well for images

2023-09-14 16:45 UTC, ozhang22 commented on content/espanol/android-tictactoe/answer-key.md
> +### Puzzle 3
nit: Translate these headers

2023-09-14 16:45 UTC, ozhang22 commented on content/espanol/android-tictactoe/booleans.md
> +Los booleanos son declaraciones verdaderas o falsas. A diferencia de las cadenas o los números, los booleanos almacenan declaraciones de verdad: ¿lo que estoy diciendo es verdadero o falso? Por ejemp
```suggestion
Los booleanos son declaraciones `true` (verdaderas) o `false` (falsas). A diferencia de las cadenas o los números, los booleanos almacenan declaraciones de verdad: ¿lo que estoy diciendo es verdadero o falso? Por ejemplo, si pregunto: "¿Eres un robot?", Esta pregunta produce un resultado verdadero o falso, que llamamos booleano. En este caso, como no eres un robot (¡con suerte!), produciríamos falso. También podemos usar operadores matemáticos para crear expresiones booleanas. Aquí hay algunos ejemplos; Sin embargo, observe los símbolos inusuales para "igual a" y "no igual a":
```

2023-09-14 16:45 UTC, ozhang22 commented on content/espanol/android-tictactoe/booleans.md
> +Elimine todo el texto ´System.out.println´ en su código. Intenta adivinar las respuestas a las siguientes expresiones. Utilice ´System.out.println´ para comprobar sus respuestas.
Make sure all ´ are replaced by `


```suggestion
Elimine todo el texto `System.out.println` en su código. Intenta adivinar las respuestas a las siguientes expresiones. Utilice `System.out.println` para comprobar sus respuestas.
```

2023-09-14 16:45 UTC, ozhang22 commented on content/espanol/android-tictactoe/printconsole.md
> +1. Sin quitar las comillas, intente cambiar ""Reiniciando el juego Tac-Tic-Toe!" ` a `"Reiniciando el juego Tic-Tac-Toe!" ` o cualquier otra frase que te guste. Presione ejecutar para ver si algo cam
```suggestion
1. Sin quitar las comillas, intente cambiar `"Reiniciando el juego Tac-Tic-Toe!"` a `"Reiniciando el juego Tic-Tac-Toe!" ` o cualquier otra frase que te guste. Presione ejecutar para ver si algo cambia.
```

2023-09-14 16:45 UTC, ozhang22 commented on content/espanol/android-tictactoe/puzzle1.md
> +Haga doble clic en el archivo `strings.xml` en los valores de → de → de la aplicación:
Can you check this line again? Seems a bit weird

2023-09-14 16:45 UTC, ozhang22 commented on content/espanol/android-tictactoe/strings.md
> +Delete all your `System.out.println` text in your code. Start your code with the line `System.out.println("Nuevo" + " " + "Foundation");`. Note that there are many ways to combine strings together. F
To remove

2023-09-14 16:45 UTC, ozhang22 commented on content/espanol/android-tictactoe/puzzle2.md
> +Ve a **MainActivity.kt** y encuentra `// PUZZLE 2` en el código y escribe un toast que de la bienvenida al usuario a tu juego con "Bienvenido al juego del Gato". Ahora presiona el botón de inicio (►)
Translation missing

2023-09-14 16:45 UTC, ozhang22 commented on content/espanol/android-tictactoe/android-setup.md
> +1. Click the Windows icon in the lower left hand corner of your computer.
Missing translations

2023-09-14 17:26 UTC, alemcuevas commented
@ozhang22 can you please review it again? I corrected all the missing translations. Thanks!

2023-09-14 19:02 UTC, ozhang22 reviewed
Just a few more formatting issues, but looks good.

2023-09-14 19:02 UTC, ozhang22 commented on content/espanol/android-tictactoe/booleans.md
> +- false == false
```suggestion
- `54 < (10 + 32)`
- `(37 / 5) == 7`
- `"Hola" + "Mundo" == "Hola Mundo"`
- `false == false`
```

2023-09-14 19:02 UTC, ozhang22 commented on content/espanol/android-tictactoe/booleans.md
> +En resumen, ´&&´ requiere que ambas expresiones booleanas sean verdaderas, mientras que ´||´ sólo requiere que una de las dos expresiones booleanas sea verdadera. Aquí hay algunos ejemplos más:
```suggestion
En resumen, `&&` requiere que ambas expresiones booleanas sean verdaderas, mientras que `||` sólo requiere que una de las dos expresiones booleanas sea verdadera. Aquí hay algunos ejemplos más:
```

2023-09-14 19:23 UTC, alemcuevas commented
@beagandica would you mind double checking this PR? Thanks!

2023-09-25 20:15 UTC, beagandica requested changes
Ale, thank you so much for doing this work!
I made comments but in general:
- use Tu vs Usted as it is for kids
- Instead of Gato game, let's use Tres en raya (i added two options for you to decide)
- The code (.xml, .gradle, .kt, etc) should the comments and details be translated as well or ok to leave in english? i believe english should be fine

CC @ozhang22 / @oliver-zhang-neuvo

2023-09-25 20:15 UTC, beagandica commented on content/espanol/android-tictactoe/resources/_gen/files/TicTacToe/build.gradle
> +        // NOTE: Do not place your application dependencies here; they belong
esto hay q ponerlo en espanol? si es asi, hay q cambiarlo en todos lados.

2023-09-25 20:15 UTC, beagandica commented on content/espanol/android-tictactoe/resources/_gen/images/activity_main.png
Ale, hay manera de que puedas recrear esta imagen y colocar en espanol? o no?
si es no, no pasa nada.

2023-09-25 20:15 UTC, beagandica commented on content/espanol/android-tictactoe/resources/_gen/images/main_layout.png
lo mismo con esta - si se puede recreas seria super

2023-09-25 20:15 UTC, beagandica commented on content/espanol/android-tictactoe/strings.md
> +Todo lo que está rodeado de comillas se denomina cadena. Así es como una computadora representa palabras u oraciones. Por ejemplo, `"a"`, `"2"`, `"banana!" `, y `"Hello World"` son cadenas, pero `Hel
cadena o string en ingles.
como es la primera vez, vale la pena colocarlo. que piensas?

2023-09-25 20:15 UTC, beagandica commented on content/espanol/android-tictactoe/strings.md
> +## Trabajando Juntos
creo q falta una linea entre linea 12 y 13

2023-09-25 20:15 UTC, beagandica commented on content/espanol/android-tictactoe/strings.md
> +Elimina todo el texto `System.out.println` en su código. Inicia su código con la línea `System.out.println("Nuevo" + " " + "Foundation");`. Ten en cuenta que hay muchas maneras de combinar cadenas. P
deberia ser **Nuevo Foundation**, no Fundacion Nuevo

2023-09-25 20:15 UTC, beagandica commented on content/espanol/android-tictactoe/resources/_gen/files/TicTacToe/app/proguard-rules.pro
> +# Add project specific ProGuard rules here.
igual aqui, esto deberia ser en espanol o dejarlo asi, no lo se @ozhang22 @oliver-zhang-neuvo

2026-04-25 05:37 UTC, beagandica commented
Thank you for your Spanish translation work! Closing as this appears to be superseded by your more recent PR #585. Please let us know if #585 captures all the updates. 🙏

2026-04-25 05:37 UTC, closed without merging